apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      memory: 2Gi
      cpu: 2000m
    defaultRequest:
      memory: 1Gi
      cpu: 1000m
    type: Container
